# Generated by Django 4.1.1 on 2022-10-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_customer_address_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catogory',
            old_name='catogory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='catogory',
            old_name='product_catogry',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='catogory',
            new_name='category',
        ),
    ]
