# Generated by Django 4.1.1 on 2022-10-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_category1_category2_alter_products_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category2',
            old_name='product_category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='category2',
            name='category2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
