# Generated by Django 4.1.1 on 2022-10-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_rename_category_products_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category1'),
        ),
    ]
