# Generated by Django 4.1.1 on 2022-10-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_products_category2_alter_products_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
