# Generated by Django 4.1.1 on 2022-10-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_remove_products_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category2',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
